# permissions for end users to edit axonopscassandras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: axonops-developer-operator
    app.kubernetes.io/managed-by: kustomize
  name: axonopscassandra-editor-role
rules:
- apiGroups:
  - cassandra.axonops.com
  resources:
  - axonopscassandras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cassandra.axonops.com
  resources:
  - axonopscassandras/status
  verbs:
  - get
