---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cassandra.axonops.com.axonops.com
  resources:
  - axonopscassandras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cassandra.axonops.com.axonops.com
  resources:
  - axonopscassandras/finalizers
  verbs:
  - update
- apiGroups:
  - cassandra.axonops.com.axonops.com
  resources:
  - axonopscassandras/status
  verbs:
  - get
  - patch
  - update
