apiVersion: axonops.com/v1beta1
kind: AxonOpsCassandra
metadata:
  labels:
    app.kubernetes.io/name: axonops-developer-operator
    app.kubernetes.io/managed-by: kustomize
  name: axonopscassandra-sample
  namespace: axonops-dev
spec:
  cassandra:
    replicas: 1
    clusterName: "my-dev-env"
    image:
      tag: "5.0"
  axonops:
    elasticsearch:
      persistentVolume:
        size: 2Gi
        storageClass: local-path
    dashboard:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      ingress:
        enabled: true
        ingressClassName: traefik
        labels:
          hello: world
        hosts:
          - axonops-dev.localhost
