apiVersion: cassandra.axonops.com.axonops.com/v1beta1
kind: AxonOpsCassandra
metadata:
  labels:
    app.kubernetes.io/name: axonops-developer-operator
    app.kubernetes.io/managed-by: kustomize
  name: axonopscassandra-sample
spec:
  # TODO(user): Add fields here
