{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: axonops-developer-operator
  labels:
    {{- include "axonops-developer-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "networking"
  resources:
  - "ingresses"
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "update"
  - "delete"
  - "create"
- apiGroups:
  - "apps"
  resources:
  - "ingresses"
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "update"
  - "delete"
  - "create"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "patch"
- apiGroups:
  - "cassandra.axonops.com"
  resources:
  - "axonopscassandra"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "update"
  - "delete"
  - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: axonops-developer-operator
  labels:
    {{- include "axonops-developer-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: axonops-developer-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "axonops-developer-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axonops-developer-operator.serviceAccountName" . }}
  labels:
    {{- include "axonops-developer-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
